### model
model_name_or_path: Qwen/Qwen2-7B-Instruct-AWQ
quantization_bit: 2
quantization_method: hqq  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: zyfg-fl-part
template: qwen
cutoff_len: 8000
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 1

### output
output_dir: saves/Qwen2-7B-int4-Chat/lora/train_2024-09-05-04-31-05
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
num_train_epochs: 20.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
max_grad_norm: 1.0
warmup_steps: 0
include_num_input_tokens_seen: true
lora_rank: 8
lora_alpha: 16
lora_dropout: 0
lora_target: all
flash_attn: auto
optim: adamw_torch
packing: false
report_to: none

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
